version: '3.5'

services:
  db:
    image: postgres:10
    container_name: postgresql
    restart: always
    # Optional: Map the container port to a host port to be able to connect with a local db client
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
      target: dev
    restart: always
    container_name: sistema
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - PURCHASE_TIER_1=${PURCHASE_TIER_1}
      - PURCHASE_TIER_1_PERCENTAGE=${PURCHASE_TIER_1_PERCENTAGE}
      - PURCHASE_TIER_2=${PURCHASE_TIER_2}
      - PURCHASE_TIER_2_PERCENTAGE=${PURCHASE_TIER_2_PERCENTAGE}
      - PURCHASE_TIER_3=${PURCHASE_TIER_3}
      - PURCHASE_TIER_3_PERCENTAGE=${PURCHASE_TIER_3_PERCENTAGE}
      - APPEND_SLASH=${APPEND_SLASH}
      - BOTICARIO_API_URL=${BOTICARIO_API_URL}
      - BOTICARIO_API_TOKEN=${BOTICARIO_API_TOKEN}
      - CPF_EXCEPTION=${CPF_EXCEPTION}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}
    volumes:
      - ../:/home/web/code
    ports:
      - 8000:8000

volumes:
  postgres_data: