# Generated by Django 4.0.6 on 2022-08-01 22:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revendedor', '0002_alter_revendedoruser_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='código')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('data', models.DateField(auto_now_add=True, verbose_name='data')),
                ('status', models.CharField(choices=[('v', 'Em validação'), ('A', 'Aprovado')], default='v', max_length=2)),
                ('porcentagem', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de cashback')),
                ('valor_cashback', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='cpf')),
            ],
        ),
    ]
