# Generated by Django 4.0.6 on 2022-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendedor', '0004_createsuperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('V', 'Em validação'), ('A', 'Aprovado')], default='V', max_length=1),
        ),
    ]
