# Generated by Django 4.0.6 on 2022-08-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendedor', '0005_alter_compra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(verbose_name='data'),
        ),
    ]
